sonar.projectKey=ifs24039-pabwe2026-nextjs
sonar.projectName=ifs24039-pabwe2026-nextjs
 
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
 
sonar.sourceEncoding=UTF-8
 
sonar.javascript.lcov.reportPaths=coverage/lcov.info
 
sonar.exclusions=node_modules/**,coverage/**,.next/**,src/app/**,src/types/**,src/server.ts,src/lib/config.ts,src/components/Providers.tsx,src/setupTests.ts,src/test-utils.tsx,**/*.test.ts,**/*.test.tsx